apiVersion: v1
kind: Namespace
metadata:
  name: elasticweb-test
  labels:
    name: elasticweb-test
---
apiVersion: elasticweb.com.bolingcavalry/v1
kind: ElasticWeb
metadata:
  namespace: elasticweb-test
  labels:
    app.kubernetes.io/name: elasticweb
    app.kubernetes.io/managed-by: kustomize
  name: elasticweb-sample
spec:
  image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/tomcat:8.0
  port: 30003
  singlePodQPS: 900
  #totalQPS: 600
